# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client-comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63lient-comm.proto\x12\x06stream\"6\n\x11UploadFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"!\n\x0fUploadFileReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\'\n\x13\x44ownloadFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"$\n\x11\x44ownloadFileReply\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x32\x9d\x01\n\tStreaming\x12\x44\n\nUploadFile\x12\x19.stream.UploadFileRequest\x1a\x17.stream.UploadFileReply\"\x00(\x01\x12J\n\x0c\x44ownloadFile\x12\x1b.stream.DownloadFileRequest\x1a\x19.stream.DownloadFileReply\"\x00\x30\x01\x42\x15\n\x11org.client.protosP\x01\x62\x06proto3')



_UPLOADFILEREQUEST = DESCRIPTOR.message_types_by_name['UploadFileRequest']
_UPLOADFILEREPLY = DESCRIPTOR.message_types_by_name['UploadFileReply']
_DOWNLOADFILEREQUEST = DESCRIPTOR.message_types_by_name['DownloadFileRequest']
_DOWNLOADFILEREPLY = DESCRIPTOR.message_types_by_name['DownloadFileReply']
UploadFileRequest = _reflection.GeneratedProtocolMessageType('UploadFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADFILEREQUEST,
  '__module__' : 'client_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.UploadFileRequest)
  })
_sym_db.RegisterMessage(UploadFileRequest)

UploadFileReply = _reflection.GeneratedProtocolMessageType('UploadFileReply', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADFILEREPLY,
  '__module__' : 'client_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.UploadFileReply)
  })
_sym_db.RegisterMessage(UploadFileReply)

DownloadFileRequest = _reflection.GeneratedProtocolMessageType('DownloadFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADFILEREQUEST,
  '__module__' : 'client_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.DownloadFileRequest)
  })
_sym_db.RegisterMessage(DownloadFileRequest)

DownloadFileReply = _reflection.GeneratedProtocolMessageType('DownloadFileReply', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADFILEREPLY,
  '__module__' : 'client_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.DownloadFileReply)
  })
_sym_db.RegisterMessage(DownloadFileReply)

_STREAMING = DESCRIPTOR.services_by_name['Streaming']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021org.client.protosP\001'
  _UPLOADFILEREQUEST._serialized_start=29
  _UPLOADFILEREQUEST._serialized_end=83
  _UPLOADFILEREPLY._serialized_start=85
  _UPLOADFILEREPLY._serialized_end=118
  _DOWNLOADFILEREQUEST._serialized_start=120
  _DOWNLOADFILEREQUEST._serialized_end=159
  _DOWNLOADFILEREPLY._serialized_start=161
  _DOWNLOADFILEREPLY._serialized_end=197
  _STREAMING._serialized_start=200
  _STREAMING._serialized_end=357
# @@protoc_insertion_point(module_scope)
