apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-node-deployment
spec:
  selector:
    matchLabels:
      app: master-node
  replicas: 3
  template:
    metadata:
      labels:
        app: master-node
    spec:
      containers:
      - name: master-node 
        image: anupriyar/master-node
        ports:
        - containerPort: 6090
---        
apiVersion: v1
kind: Service
metadata:
  name: master-node-service
spec:
  ports:
  - protocol: "TCP"
    port: 6090
    targetPort: 6090
  type: LoadBalancer
    