# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master-comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11master-comm.proto\x12\x06stream\"\"\n\x0eNodeIpsRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x0cNodeIpsReply\x12\x0f\n\x07nodeips\x18\x01 \x03(\t\">\n\x19ReplicationDetailsRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07nodeips\x18\x02 \x03(\t\"\x1c\n\x1aReplicationDetailsResponse2\xbd\x01\n\x0bReplication\x12J\n\x18GetNodeIpsForReplication\x12\x16.stream.NodeIpsRequest\x1a\x14.stream.NodeIpsReply\"\x00\x12\x62\n\x17UpdateReplicationStatus\x12!.stream.ReplicationDetailsRequest\x1a\".stream.ReplicationDetailsResponse\"\x00\x42\x15\n\x11org.master.protosP\x01\x62\x06proto3')



_NODEIPSREQUEST = DESCRIPTOR.message_types_by_name['NodeIpsRequest']
_NODEIPSREPLY = DESCRIPTOR.message_types_by_name['NodeIpsReply']
_REPLICATIONDETAILSREQUEST = DESCRIPTOR.message_types_by_name['ReplicationDetailsRequest']
_REPLICATIONDETAILSRESPONSE = DESCRIPTOR.message_types_by_name['ReplicationDetailsResponse']
NodeIpsRequest = _reflection.GeneratedProtocolMessageType('NodeIpsRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODEIPSREQUEST,
  '__module__' : 'master_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.NodeIpsRequest)
  })
_sym_db.RegisterMessage(NodeIpsRequest)

NodeIpsReply = _reflection.GeneratedProtocolMessageType('NodeIpsReply', (_message.Message,), {
  'DESCRIPTOR' : _NODEIPSREPLY,
  '__module__' : 'master_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.NodeIpsReply)
  })
_sym_db.RegisterMessage(NodeIpsReply)

ReplicationDetailsRequest = _reflection.GeneratedProtocolMessageType('ReplicationDetailsRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATIONDETAILSREQUEST,
  '__module__' : 'master_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.ReplicationDetailsRequest)
  })
_sym_db.RegisterMessage(ReplicationDetailsRequest)

ReplicationDetailsResponse = _reflection.GeneratedProtocolMessageType('ReplicationDetailsResponse', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATIONDETAILSRESPONSE,
  '__module__' : 'master_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.ReplicationDetailsResponse)
  })
_sym_db.RegisterMessage(ReplicationDetailsResponse)

_REPLICATION = DESCRIPTOR.services_by_name['Replication']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021org.master.protosP\001'
  _NODEIPSREQUEST._serialized_start=29
  _NODEIPSREQUEST._serialized_end=63
  _NODEIPSREPLY._serialized_start=65
  _NODEIPSREPLY._serialized_end=96
  _REPLICATIONDETAILSREQUEST._serialized_start=98
  _REPLICATIONDETAILSREQUEST._serialized_end=160
  _REPLICATIONDETAILSRESPONSE._serialized_start=162
  _REPLICATIONDETAILSRESPONSE._serialized_end=190
  _REPLICATION._serialized_start=193
  _REPLICATION._serialized_end=382
# @@protoc_insertion_point(module_scope)
