# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_comm_pb2 as master__comm__pb2


class ReplicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNodeIpsForReplication = channel.unary_unary(
                '/stream.Replication/GetNodeIpsForReplication',
                request_serializer=master__comm__pb2.NodeIpsRequest.SerializeToString,
                response_deserializer=master__comm__pb2.NodeIpsReply.FromString,
                )
        self.UpdateReplicationStatus = channel.unary_unary(
                '/stream.Replication/UpdateReplicationStatus',
                request_serializer=master__comm__pb2.ReplicationDetailsRequest.SerializeToString,
                response_deserializer=master__comm__pb2.ReplicationDetailsResponse.FromString,
                )


class ReplicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNodeIpsForReplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReplicationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNodeIpsForReplication': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeIpsForReplication,
                    request_deserializer=master__comm__pb2.NodeIpsRequest.FromString,
                    response_serializer=master__comm__pb2.NodeIpsReply.SerializeToString,
            ),
            'UpdateReplicationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReplicationStatus,
                    request_deserializer=master__comm__pb2.ReplicationDetailsRequest.FromString,
                    response_serializer=master__comm__pb2.ReplicationDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream.Replication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Replication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNodeIpsForReplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stream.Replication/GetNodeIpsForReplication',
            master__comm__pb2.NodeIpsRequest.SerializeToString,
            master__comm__pb2.NodeIpsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateReplicationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stream.Replication/UpdateReplicationStatus',
            master__comm__pb2.ReplicationDetailsRequest.SerializeToString,
            master__comm__pb2.ReplicationDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
