# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node-comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnode-comm.proto\x12\x06stream\"9\n\x14\x43reateReplicaRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"$\n\x12\x43reateReplicaReply\x12\x0e\n\x06status\x18\x01 \x01(\t2`\n\x0fNodeReplication\x12M\n\rCreateReplica\x12\x1c.stream.CreateReplicaRequest\x1a\x1a.stream.CreateReplicaReply\"\x00(\x01\x42\x13\n\x0forg.node.protosP\x01\x62\x06proto3')



_CREATEREPLICAREQUEST = DESCRIPTOR.message_types_by_name['CreateReplicaRequest']
_CREATEREPLICAREPLY = DESCRIPTOR.message_types_by_name['CreateReplicaReply']
CreateReplicaRequest = _reflection.GeneratedProtocolMessageType('CreateReplicaRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREPLICAREQUEST,
  '__module__' : 'node_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.CreateReplicaRequest)
  })
_sym_db.RegisterMessage(CreateReplicaRequest)

CreateReplicaReply = _reflection.GeneratedProtocolMessageType('CreateReplicaReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREPLICAREPLY,
  '__module__' : 'node_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.CreateReplicaReply)
  })
_sym_db.RegisterMessage(CreateReplicaReply)

_NODEREPLICATION = DESCRIPTOR.services_by_name['NodeReplication']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017org.node.protosP\001'
  _CREATEREPLICAREQUEST._serialized_start=27
  _CREATEREPLICAREQUEST._serialized_end=84
  _CREATEREPLICAREPLY._serialized_start=86
  _CREATEREPLICAREPLY._serialized_end=122
  _NODEREPLICATION._serialized_start=124
  _NODEREPLICATION._serialized_end=220
# @@protoc_insertion_point(module_scope)
