apiVersion: v1
kind: Service
metadata:
  name: redis-external
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: redis-0
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379